services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    privileged: true
    ports:
        - 2000:2000
    volumes:
        - ./data/piston/packages:/piston/packages
    tmpfs:
        - /tmp:exec
  backend:
    build:
      context: apps/backend/
      dockerfile: Dockerfile
    image: code01-backend:latest
    container_name: code01-backend
    depends_on:
      - piston
    ports:
      - "3001:3001"
    environment:
      - PYTHONUNBUFFERED=1
      - PISTON_API_URL=http://piston:2000
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://127.0.0.1:3001 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
      - apparmor:unconfined
    devices:
      - /dev/random:/dev/random
    volumes:
      - piston-data:/piston
      - isolate-data:/app/isolate
    privileged: true
    restart: unless-stopped

  frontend:
    build:
      context: apps/frontend/
      dockerfile: Dockerfile
    image: code01-frontend:latest
    container_name: code01-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

volumes:
  piston-data:
  isolate-data:
